#if !canImport(ObjectiveC)
import XCTest

extension AngleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AngleTests = [
        ("testAcosFirstQuadrant", testAcosFirstQuadrant),
        ("testAcosSecondQuadrant", testAcosSecondQuadrant),
        ("testAddition", testAddition),
        ("testAsinFirstQuadrant", testAsinFirstQuadrant),
        ("testAsinFourthQuadrant", testAsinFourthQuadrant),
        ("testAtanFirstQuadrant", testAtanFirstQuadrant),
        ("testAtanFourthQuadrant", testAtanFourthQuadrant),
        ("testAtanSecondQuadrant", testAtanSecondQuadrant),
        ("testAtanThirdQuadrant", testAtanThirdQuadrant),
        ("testComparable1", testComparable1),
        ("testComparable2", testComparable2),
        ("testConstructor", testConstructor),
        ("testCosFirstQuadrant", testCosFirstQuadrant),
        ("testCosFourthQuadrant", testCosFourthQuadrant),
        ("testCosSecondQuadrant", testCosSecondQuadrant),
        ("testCosThirdQuadrant", testCosThirdQuadrant),
        ("testEquality1", testEquality1),
        ("testEquality2", testEquality2),
        ("testPrefix", testPrefix),
        ("testRadians", testRadians),
        ("testSinFirstQuadrant", testSinFirstQuadrant),
        ("testSinFourthQuadrant", testSinFourthQuadrant),
        ("testSinSecondQuadrant", testSinSecondQuadrant),
        ("testSinThirdQuadrant", testSinThirdQuadrant),
        ("testSubtraction", testSubtraction),
        ("testTanFirstQuadrant", testTanFirstQuadrant),
        ("testTanFourthQuadrant", testTanFourthQuadrant),
        ("testTanSecondQuadrant", testTanSecondQuadrant),
        ("testTanThirdQuadrant", testTanThirdQuadrant),
    ]
}

extension BoundsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoundsTests = [
        ("testIntersectionOfAdjacentBounds", testIntersectionOfAdjacentBounds),
        ("testIntersectionOfBoundsAndEmpty", testIntersectionOfBoundsAndEmpty),
        ("testIntersectionOfCoincidingBounds", testIntersectionOfCoincidingBounds),
        ("testIntersectionOfEmptyAndBounds", testIntersectionOfEmptyAndBounds),
        ("testUnionOfAdjacentBounds", testUnionOfAdjacentBounds),
        ("testUnionOfBoundsAndEmpty", testUnionOfBoundsAndEmpty),
        ("testUnionOfCoincidingBounds", testUnionOfCoincidingBounds),
        ("testUnionOfEmptyAndBounds", testUnionOfEmptyAndBounds),
    ]
}

extension CGPathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CGPathTests = [
        ("testClosedLineAndQuadCurveCGPath", testClosedLineAndQuadCurveCGPath),
        ("testRectangularCGPath", testRectangularCGPath),
        ("testRoundedRectCGPath", testRoundedRectCGPath),
        ("testUnclosedLineAndCubicCurveCGPath", testUnclosedLineAndCubicCurveCGPath),
        ("testUnclosedLineAndQuadCurveCGPath", testUnclosedLineAndQuadCurveCGPath),
    ]
}

extension CSGTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSGTests = [
        ("testIntersectionOfAdjacentBoxes", testIntersectionOfAdjacentBoxes),
        ("testIntersectionOfAdjacentSquares", testIntersectionOfAdjacentSquares),
        ("testIntersectionOfCoincidingBoxes", testIntersectionOfCoincidingBoxes),
        ("testIntersectionOfCoincidingSquares", testIntersectionOfCoincidingSquares),
        ("testIntersectionOfOverlappingBoxes", testIntersectionOfOverlappingBoxes),
        ("testIntersectionOfOverlappingSquares", testIntersectionOfOverlappingSquares),
        ("testSubtractAdjacentBoxes", testSubtractAdjacentBoxes),
        ("testSubtractAdjacentSquares", testSubtractAdjacentSquares),
        ("testSubtractCoincidingBoxes", testSubtractCoincidingBoxes),
        ("testSubtractCoincidingBoxesWhenTriangulated", testSubtractCoincidingBoxesWhenTriangulated),
        ("testSubtractCoincidingSquares", testSubtractCoincidingSquares),
        ("testSubtractOverlappingBoxes", testSubtractOverlappingBoxes),
        ("testSubtractOverlappingSquares", testSubtractOverlappingSquares),
        ("testUnionOfAdjacentBoxes", testUnionOfAdjacentBoxes),
        ("testUnionOfAdjacentSquares", testUnionOfAdjacentSquares),
        ("testUnionOfCoincidingBoxes", testUnionOfCoincidingBoxes),
        ("testUnionOfCoincidingSquares", testUnionOfCoincidingSquares),
        ("testUnionOfOverlappingBoxes", testUnionOfOverlappingBoxes),
        ("testUnionOfOverlappingSquares", testUnionOfOverlappingSquares),
        ("testXorAdjacentCubes", testXorAdjacentCubes),
        ("testXorAdjacentSquares", testXorAdjacentSquares),
        ("testXorCoincidingCubes", testXorCoincidingCubes),
        ("testXorCoincidingSquares", testXorCoincidingSquares),
        ("testXorOverlappingCubes", testXorOverlappingCubes),
        ("testXorOverlappingSquares", testXorOverlappingSquares),
    ]
}

extension CodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTests = [
        ("testDecodingAngle", testDecodingAngle),
        ("testDecodingAngle2", testDecodingAngle2),
        ("testDecodingAngle3", testDecodingAngle3),
        ("testDecodingAxisAngleRotation", testDecodingAxisAngleRotation),
        ("testDecodingCurvedPathPoint2", testDecodingCurvedPathPoint2),
        ("testDecodingCurvedUnkeyedPathPoint3", testDecodingCurvedUnkeyedPathPoint3),
        ("testDecodingDirection2", testDecodingDirection2),
        ("testDecodingDirection3", testDecodingDirection3),
        ("testDecodingDistance2", testDecodingDistance2),
        ("testDecodingDistance3", testDecodingDistance3),
        ("testDecodingIdentityRotation", testDecodingIdentityRotation),
        ("testDecodingInvalidDirections", testDecodingInvalidDirections),
        ("testDecodingInvalidDistances", testDecodingInvalidDistances),
        ("testDecodingInvalidPositions", testDecodingInvalidPositions),
        ("testDecodingInvalidVectors", testDecodingInvalidVectors),
        ("testDecodingKeyedDirection", testDecodingKeyedDirection),
        ("testDecodingKeyedDistance", testDecodingKeyedDistance),
        ("testDecodingKeyedPath", testDecodingKeyedPath),
        ("testDecodingKeyedPlane", testDecodingKeyedPlane),
        ("testDecodingKeyedPosition", testDecodingKeyedPosition),
        ("testDecodingKeyedVector", testDecodingKeyedVector),
        ("testDecodingMesh", testDecodingMesh),
        ("testDecodingPathPoint2", testDecodingPathPoint2),
        ("testDecodingPathPoint3", testDecodingPathPoint3),
        ("testDecodingPitchYawRollRotation", testDecodingPitchYawRollRotation),
        ("testDecodingPolygon", testDecodingPolygon),
        ("testDecodingPolygonWithPlane", testDecodingPolygonWithPlane),
        ("testDecodingPosition2", testDecodingPosition2),
        ("testDecodingPosition3", testDecodingPosition3),
        ("testDecodingRollRotation", testDecodingRollRotation),
        ("testDecodingSimplePath", testDecodingSimplePath),
        ("testDecodingSubpath", testDecodingSubpath),
        ("testDecodingUnkeyedPlane", testDecodingUnkeyedPlane),
        ("testDecodingVector2", testDecodingVector2),
        ("testDecodingVector3", testDecodingVector3),
        ("testDecodingVertex", testDecodingVertex),
        ("testDecodingVertexWithInvalidNormal", testDecodingVertexWithInvalidNormal),
        ("testDecodingVertexWithoutTexcoord", testDecodingVertexWithoutTexcoord),
        ("testEncodeAndDecodingRotation", testEncodeAndDecodingRotation),
        ("testEncodingDirection2", testEncodingDirection2),
        ("testEncodingDirection3", testEncodingDirection3),
        ("testEncodingDistance2", testEncodingDistance2),
        ("testEncodingDistance3", testEncodingDistance3),
        ("testEncodingPlane", testEncodingPlane),
        ("testEncodingPolygonWithDataMaterial", testEncodingPolygonWithDataMaterial),
        ("testEncodingPolygonWithIntMaterial", testEncodingPolygonWithIntMaterial),
        ("testEncodingPolygonWithNilMaterial", testEncodingPolygonWithNilMaterial),
        ("testEncodingPolygonWithOSColorMaterial", testEncodingPolygonWithOSColorMaterial),
        ("testEncodingPolygonWithStringMaterial", testEncodingPolygonWithStringMaterial),
        ("testEncodingPolygonWithUnsupportedMaterial", testEncodingPolygonWithUnsupportedMaterial),
        ("testEncodingPosition2", testEncodingPosition2),
        ("testEncodingPosition3", testEncodingPosition3),
        ("testEncodingVector2", testEncodingVector2),
        ("testEncodingVector3", testEncodingVector3),
        ("testKeylessPolygon", testKeylessPolygon),
    ]
}

extension DirectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectionTests = [
        ("testAngleWithOtherDirection0Degrees", testAngleWithOtherDirection0Degrees),
        ("testAngleWithOtherDirection45Degrees", testAngleWithOtherDirection45Degrees),
        ("testAngleWithOtherDirection45DegreesOppositeSide", testAngleWithOtherDirection45DegreesOppositeSide),
        ("testAngleWithOtherDirection90Degrees", testAngleWithOtherDirection90Degrees),
        ("testAntiparallelDirections", testAntiparallelDirections),
        ("testCrossProductGeneral", testCrossProductGeneral),
        ("testCrossProductNegativeXAxis", testCrossProductNegativeXAxis),
        ("testCrossProductNegativeZAxis", testCrossProductNegativeZAxis),
        ("testCrossProductXAxis", testCrossProductXAxis),
        ("testCrossProductZAxis", testCrossProductZAxis),
        ("testDotProductObliqueAngle", testDotProductObliqueAngle),
        ("testDotProductObtuseAngle", testDotProductObtuseAngle),
        ("testGeneralDirections", testGeneralDirections),
        ("testNormalDirections", testNormalDirections),
        ("testNormedAddition", testNormedAddition),
        ("testNormedAdditionOnXYPlane", testNormedAdditionOnXYPlane),
        ("testNormedAdditionOnXZPlane", testNormedAdditionOnXZPlane),
        ("testNormedAdditionOnYZPlane", testNormedAdditionOnYZPlane),
        ("testNormedComponents", testNormedComponents),
        ("testNormedSubtractionOnXYPlane", testNormedSubtractionOnXYPlane),
        ("testNormedSubtractionOnXZPlane", testNormedSubtractionOnXZPlane),
        ("testNormedSubtractionOnYZPlane", testNormedSubtractionOnYZPlane),
        ("testParallelDirections", testParallelDirections),
        ("testRotateAroundNonNormalDirection", testRotateAroundNonNormalDirection),
        ("testRotateXAxis", testRotateXAxis),
        ("testRotateYAxis", testRotateYAxis),
    ]
}

extension DistanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DistanceTests = [
        ("testAddition", testAddition),
        ("testAntiparallelDistances", testAntiparallelDistances),
        ("testComponents", testComponents),
        ("testCrossProduct1", testCrossProduct1),
        ("testCrossProduct1DifferentOrder", testCrossProduct1DifferentOrder),
        ("testCrossProduct2", testCrossProduct2),
        ("testCrossProduct2DifferentOrder", testCrossProduct2DifferentOrder),
        ("testDistance", testDistance),
        ("testGeneralDistances", testGeneralDistances),
        ("testNorm", testNorm),
        ("testNormalComponentTest1", testNormalComponentTest1),
        ("testNormalComponentTest2", testNormalComponentTest2),
        ("testNormalDistances", testNormalDistances),
        ("testOperatorDoubleMultiplyWithDirection", testOperatorDoubleMultiplyWithDirection),
        ("testParallelDistances", testParallelDistances),
        ("testRotated", testRotated),
        ("testScalarDivide", testScalarDivide),
        ("testScalarMultiply", testScalarMultiply),
        ("testSubtraction", testSubtraction),
        ("testZeroDistance", testZeroDistance),
    ]
}

extension LineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LineTests = [
        ("testDistanceFromPointHarder", testDistanceFromPointHarder),
        ("testDistanceFromPointSimple", testDistanceFromPointSimple),
        ("testLineIntersectionXY", testLineIntersectionXY),
        ("testLineIntersectionXZ", testLineIntersectionXZ),
        ("testLineIntersectionYZ", testLineIntersectionYZ),
    ]
}

extension PathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathTests = [
        ("testClipClosedClockwiseTriangleMostlyRightOfAxis", testClipClosedClockwiseTriangleMostlyRightOfAxis),
        ("testClipClosedClockwiseTriangleToRightOfAxis", testClipClosedClockwiseTriangleToRightOfAxis),
        ("testClipClosedRectangleSpanningAxis", testClipClosedRectangleSpanningAxis),
        ("testClosedAnticlockwiseTriangleLeftOfAxis", testClosedAnticlockwiseTriangleLeftOfAxis),
        ("testConcaveClosedPathAnticlockwiseWinding", testConcaveClosedPathAnticlockwiseWinding),
        ("testConcaveClosedPathClockwiseWinding", testConcaveClosedPathClockwiseWinding),
        ("testConcaveClosedPathClockwiseWinding2", testConcaveClosedPathClockwiseWinding2),
        ("testConcaveOpenPathAnticlockwiseWinding", testConcaveOpenPathAnticlockwiseWinding),
        ("testConcaveOpenPathClockwiseWinding", testConcaveOpenPathClockwiseWinding),
        ("testConvexClosedPathAnticlockwiseWinding", testConvexClosedPathAnticlockwiseWinding),
        ("testConvexClosedPathClockwiseWinding", testConvexClosedPathClockwiseWinding),
        ("testConvexOpenPathAnticlockwiseWinding", testConvexOpenPathAnticlockwiseWinding),
        ("testConvexOpenPathClockwiseWinding", testConvexOpenPathClockwiseWinding),
        ("testEdgeVerticesForCircle", testEdgeVerticesForCircle),
        ("testEdgeVerticesForEllipse", testEdgeVerticesForEllipse),
        ("testEdgeVerticesForSemicircle", testEdgeVerticesForSemicircle),
        ("testEdgeVerticesForSharpEdgedCylinder", testEdgeVerticesForSharpEdgedCylinder),
        ("testEdgeVerticesForSmoothedClosedRect", testEdgeVerticesForSmoothedClosedRect),
        ("testEdgeVerticesForSmoothedCylinder", testEdgeVerticesForSmoothedCylinder),
        ("testEdgeVerticesForVerticalPath", testEdgeVerticesForVerticalPath),
        ("testFaceVerticesForConcaveClockwisePath", testFaceVerticesForConcaveClockwisePath),
        ("testFaceVerticesForDegenerateClosedAnticlockwisePath", testFaceVerticesForDegenerateClosedAnticlockwisePath),
        ("testOverlappingClosedQuad", testOverlappingClosedQuad),
        ("testOverlappingOpenQuad", testOverlappingOpenQuad),
        ("testPathWithConjoinedLoopsHasCorrectSubpaths", testPathWithConjoinedLoopsHasCorrectSubpaths),
        ("testPathWithLineEndingInLoopHasCorrectSubpaths", testPathWithLineEndingInLoopHasCorrectSubpaths),
        ("testPathWithLoopEndingInLineHasCorrectSubpaths", testPathWithLoopEndingInLineHasCorrectSubpaths),
        ("testPathWithTwoSeparateLoopsHasCorrectSubpaths", testPathWithTwoSeparateLoopsHasCorrectSubpaths),
        ("testSimpleClosedPathHasNoSubpaths", testSimpleClosedPathHasNoSubpaths),
        ("testSimpleClosedQuad", testSimpleClosedQuad),
        ("testSimpleClosedTriangle", testSimpleClosedTriangle),
        ("testSimpleLine", testSimpleLine),
        ("testSimpleOpenPathHasNoSubpaths", testSimpleOpenPathHasNoSubpaths),
        ("testSimpleOpenQuad", testSimpleOpenQuad),
        ("testSimpleOpenTriangle", testSimpleOpenTriangle),
        ("testStraightLinePathAnticlockwiseWinding", testStraightLinePathAnticlockwiseWinding),
        ("testStraightLinePathAnticlockwiseWinding2", testStraightLinePathAnticlockwiseWinding2),
        ("testStraightLinePathAnticlockwiseWinding3", testStraightLinePathAnticlockwiseWinding3),
    ]
}

extension PlaneTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaneTests = [
        ("testConcavePolygonClockwiseWinding", testConcavePolygonClockwiseWinding),
        ("testIntersectionWithParallelPlane", testIntersectionWithParallelPlane),
        ("testIntersectionWithPerpendicularPlane", testIntersectionWithPerpendicularPlane),
        ("testIntersectionWithRandomPlane", testIntersectionWithRandomPlane),
    ]
}

extension PolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PolygonTests = [
        ("testConcaveAnticlockwisePolygonContainsPoint", testConcaveAnticlockwisePolygonContainsPoint),
        ("testConcaveAnticlockwisePolygonContainsPoint2", testConcaveAnticlockwisePolygonContainsPoint2),
        ("testConcaveAnticlockwisePolygonCorrectlyTessellated", testConcaveAnticlockwisePolygonCorrectlyTessellated),
        ("testConcaveAnticlockwisePolygonCorrectlyTriangulated", testConcaveAnticlockwisePolygonCorrectlyTriangulated),
        ("testConcavePolygonAnticlockwiseWinding", testConcavePolygonAnticlockwiseWinding),
        ("testConcavePolygonClockwiseWinding", testConcavePolygonClockwiseWinding),
        ("testConvexAnticlockwisePolygonContainsPoint", testConvexAnticlockwisePolygonContainsPoint),
        ("testConvexClockwisePolygonContainsPoint", testConvexClockwisePolygonContainsPoint),
        ("testConvexPolygonAnticlockwiseWinding", testConvexPolygonAnticlockwiseWinding),
        ("testConvexPolygonClockwiseWinding", testConvexPolygonClockwiseWinding),
        ("testDegeneratePolygonWithColinearPoints", testDegeneratePolygonWithColinearPoints),
        ("testHouseShapedPolygonCorrectlyTriangulated", testHouseShapedPolygonCorrectlyTriangulated),
        ("testInvertedConcaveAnticlockwisePolygonCorrectlyTessellated", testInvertedConcaveAnticlockwisePolygonCorrectlyTessellated),
        ("testInvertedConcaveAnticlockwisePolygonCorrectlyTriangulated", testInvertedConcaveAnticlockwisePolygonCorrectlyTriangulated),
        ("testMerge1", testMerge1),
        ("testMerge2", testMerge2),
        ("testMergeB2TAdjacentRects", testMergeB2TAdjacentRects),
        ("testMergeEdgeCase", testMergeEdgeCase),
        ("testMergeL2RAdjacentRectAndTriangle", testMergeL2RAdjacentRectAndTriangle),
        ("testMergeL2RAdjacentRects", testMergeL2RAdjacentRects),
        ("testMergeR2LAdjacentRects", testMergeR2LAdjacentRects),
        ("testMergeT2BAdjacentRects", testMergeT2BAdjacentRects),
        ("testNonDegeneratePolygonWithColinearPoints", testNonDegeneratePolygonWithColinearPoints),
        ("testPathWithZeroAreaColinearPointTriangulated", testPathWithZeroAreaColinearPointTriangulated),
        ("testPolygonWithColinearPointsCorrectlyTriangulated", testPolygonWithColinearPointsCorrectlyTriangulated),
    ]
}

extension PositionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PositionTests = [
        ("testAddDistanceToPosition", testAddDistanceToPosition),
        ("testConstructor", testConstructor),
        ("testDistanceFromPositions", testDistanceFromPositions),
        ("testNorm", testNorm),
        ("testRotated", testRotated),
        ("testSubtractDistanceToPosition", testSubtractDistanceToPosition),
    ]
}

extension SceneKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SceneKitTests = [
        ("testGeometryImportedWithCorrectDetail", testGeometryImportedWithCorrectDetail),
    ]
}

extension ShapeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShapeTests = [
        ("testCircleIsClosed", testCircleIsClosed),
        ("testClosedCurvedPath", testClosedCurvedPath),
        ("testClosedCurvedPathWithSharpFirstCorner", testClosedCurvedPathWithSharpFirstCorner),
        ("testClosedCurvedPathWithSharpSecondAndThirdCorner", testClosedCurvedPathWithSharpSecondAndThirdCorner),
        ("testClosedCurvedPathWithSharpSecondCorner", testClosedCurvedPathWithSharpSecondCorner),
        ("testCurveWithConsecutiveMixedTypePointsWithSamePosition", testCurveWithConsecutiveMixedTypePointsWithSamePosition),
        ("testLoftNonParallelEdges", testLoftNonParallelEdges),
        ("testLoftParallelEdges", testLoftParallelEdges),
        ("testSimpleCurvedPath", testSimpleCurvedPath),
        ("testSimpleCurveEndedPath", testSimpleCurveEndedPath),
    ]
}

extension TextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextTests = [
        ("testTextMeshWithAttributedString", testTextMeshWithAttributedString),
        ("testTextMeshWithString", testTextMeshWithString),
        ("testTextPaths", testTextPaths),
    ]
}

extension TransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransformTests = [
        ("testAxisAngleRotation1", testAxisAngleRotation1),
        ("testAxisAngleRotation2", testAxisAngleRotation2),
        ("testAxisAngleRotation3", testAxisAngleRotation3),
        ("testPitch", testPitch),
        ("testRoll", testRoll),
        ("testRotatePlane", testRotatePlane),
        ("testRotationMultipliedByScale", testRotationMultipliedByScale),
        ("testRotationMultipliedByTranslation", testRotationMultipliedByTranslation),
        ("testScaleMultipliedByRotation", testScaleMultipliedByRotation),
        ("testScalePlane", testScalePlane),
        ("testScalePlaneUniformly", testScalePlaneUniformly),
        ("testTransformPlane", testTransformPlane),
        ("testTransformVector", testTransformVector),
        ("testTranslatePlane", testTranslatePlane),
        ("testTranslationMultipliedByRotation", testTranslationMultipliedByRotation),
        ("testTranslationMultipliedByScale", testTranslationMultipliedByScale),
        ("testYaw", testYaw),
    ]
}

extension UtilityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilityTests = [
        ("testColinearPointsDontPreventConvexness", testColinearPointsDontPreventConvexness),
        ("testConvexnessResultNotAffectedByTranslation", testConvexnessResultNotAffectedByTranslation),
        ("testDegenerateColinearVertices", testDegenerateColinearVertices),
        ("testDegenerateVerticesWithZeroLengthEdge", testDegenerateVerticesWithZeroLengthEdge),
        ("testNonDegenerateColinearVertices", testNonDegenerateColinearVertices),
        ("testRemoveZeroAreaColinearPointRemoved", testRemoveZeroAreaColinearPointRemoved),
        ("testSanitizeInvalidClosedPath", testSanitizeInvalidClosedPath),
    ]
}

extension VectorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VectorTests = [
        ("testAngledLength", testAngledLength),
        ("testAxisAlignedLength", testAxisAlignedLength),
        ("testDistanceBehindPlane", testDistanceBehindPlane),
        ("testDistanceInFrontOfPlane", testDistanceInFrontOfPlane),
        ("testNonNormalizedAngle", testNonNormalizedAngle),
        ("testNonNormalizedAngleWithPlane", testNonNormalizedAngleWithPlane),
        ("testRightAngle", testRightAngle),
        ("testRightAngleWithPlane", testRightAngleWithPlane),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AngleTests.__allTests__AngleTests),
        testCase(BoundsTests.__allTests__BoundsTests),
        testCase(CGPathTests.__allTests__CGPathTests),
        testCase(CSGTests.__allTests__CSGTests),
        testCase(CodingTests.__allTests__CodingTests),
        testCase(DirectionTests.__allTests__DirectionTests),
        testCase(DistanceTests.__allTests__DistanceTests),
        testCase(LineTests.__allTests__LineTests),
        testCase(PathTests.__allTests__PathTests),
        testCase(PlaneTests.__allTests__PlaneTests),
        testCase(PolygonTests.__allTests__PolygonTests),
        testCase(PositionTests.__allTests__PositionTests),
        testCase(SceneKitTests.__allTests__SceneKitTests),
        testCase(ShapeTests.__allTests__ShapeTests),
        testCase(TextTests.__allTests__TextTests),
        testCase(TransformTests.__allTests__TransformTests),
        testCase(UtilityTests.__allTests__UtilityTests),
        testCase(VectorTests.__allTests__VectorTests),
    ]
}
#endif
